# longhorn-manager-metrics.yaml
apiVersion: v1
kind: Service
metadata:
  name: longhorn-manager-metrics
  namespace: longhorn-system
  labels: { app: longhorn-manager }
spec:
  clusterIP: None
  selector:
    app: longhorn-manager
  ports:
    - name: metrics
      port: 9500
      targetPort: 9500
#---
#apiVersion: networking.k8s.io/v1
#kind: NetworkPolicy
#metadata:
#  name: allow-prometheus-to-longhorn-metrics
#  namespace: longhorn-system
#spec:
#  podSelector:
#    matchLabels:
#      app: longhorn-manager
#  policyTypes: [Ingress]
#  ingress:
#    - from:
#        - namespaceSelector:
#            matchLabels:
#              kubernetes.io/metadata.name: ops-monitoring
#      ports:
#        - protocol: TCP
#          port: 9500
