controller:
  ingressClassResource:
    name: nginx-admin
    controllerValue: "k8s.io/ingress-nginx-admin"
  ingressClass: nginx-admin
  ingressClassByName: true
  watchIngressWithoutClass: false
  service:
    type: LoadBalancer
    externalTrafficPolicy: Local
    loadBalancerIP: 192.168.100.151
    annotations:
      metallb.universe.tf/address-pool: pool-vlan100-admin
