controller:
  ingressClassResource:
    name: nginx
    controllerValue: "k8s.io/ingress-nginx"
  ingressClass: nginx
  ingressClassByName: true
  watchIngressWithoutClass: false
  service:
    type: LoadBalancer
    externalTrafficPolicy: Local
    loadBalancerIP: 192.168.30.151
    annotations:
      metallb.universe.tf/address-pool: pool-vlan30-public
