apiVersion: v1
kind: Service
metadata:
  name: metallb-controller-metrics
  namespace: metallb-system
  labels:
    app: metallb
    component: controller
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "7472"
    prometheus.io/path: "/metrics"
spec:
  selector:
    app: metallb
    component: controller
  ports:
    - name: metrics
      port: 7472
      targetPort: 7472
---
apiVersion: v1
kind: Service
metadata:
  name: metallb-speaker-metrics
  namespace: metallb-system
  labels:
    app: metallb
    component: speaker
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "7472"
    prometheus.io/path: "/metrics"
spec:
  clusterIP: None
  selector:
    app: metallb
    component: speaker
  ports:
    - name: metrics
      port: 7472
      targetPort: 7472
