apiVersion: v1
kind: Namespace
metadata:
  name: ops-monitoring
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-data
  namespace: ops-monitoring
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: longhorn-2r
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: ops-monitoring
  labels: { app: grafana }
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector: { matchLabels: { app: grafana } }
  template:
    metadata: { labels: { app: grafana } }
    spec:
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
      containers:
        - name: grafana
          image: grafana/grafana:latest
          imagePullPolicy: IfNotPresent
          ports: [{ name: http, containerPort: 3000 }]
          env:
          - { name: TZ, value: Europe/Berlin }
          - { name: GF_INSTALL_PLUGINS, value: grafana-clock-panel }
          - name: GF_SECURITY_ADMIN_USER
            valueFrom:
              secretKeyRef: { name: grafana-admin, key: admin-user }
          - name: GF_SECURITY_ADMIN_PASSWORD
            valueFrom:
              secretKeyRef: { name: grafana-admin, key: admin-password }
          - name: GF_METRICS_ENABLED
            value: "true"
          volumeMounts:
            - { name: data, mountPath: /var/lib/grafana }
          readinessProbe:
            httpGet: { path: /api/health, port: http }
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet: { path: /api/health, port: http }
            initialDelaySeconds: 30
            periodSeconds: 20
          resources:
            requests: { cpu: 200m, memory: 512Mi }
            limits:   { cpu: "2",  memory: 2Gi }
      volumes:
        - name: data
          persistentVolumeClaim: { claimName: grafana-data }
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: ops-monitoring
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "3000"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  selector: { app: grafana }
  ports:
    - { name: http, port: 3000, targetPort: http }
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grafana
  namespace: ops-monitoring
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-dns
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
spec:
  ingressClassName: nginx-mgmt
  rules:
    - host: grafana.mon.rohrbom.be
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service: { name: grafana, port: { number: 3000 } }
  tls:
    - hosts: [grafana.mon.rohrbom.be]
      secretName: grafana-tls
---
# Erlaubt Traffic nur vom mgmt-Ingress-Namespace (VLAN 10) und aus ops-monitoring
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: grafana-allow-ops-and-ingress
  namespace: ops-monitoring
spec:
  podSelector: { matchLabels: { app: grafana } }
  policyTypes: [Ingress]
  ingress:
    - from:
        - namespaceSelector:
            matchLabels: { kubernetes.io/metadata.name: ops-monitoring }
        - namespaceSelector:
            matchLabels: { kubernetes.io/metadata.name: ingress-vlan10-mgmt }
      ports:
        - protocol: TCP
          port: 3000
