apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kube-vip-ds
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: kube-vip
  template:
    metadata:
      labels:
        app: kube-vip
    spec:
      hostNetwork: true
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"
      nodeSelector:
        node-role.kubernetes.io/control-plane: "true"
      containers:
        - name: kube-vip
          image: ghcr.io/kube-vip/kube-vip:v0.6.4
          args: ["manager"]
          env:
            - name: vip_address
              value: "192.168.100.100"
            - name: vip_interface
              value: "eth0"
            - name: cp_enable
              value: "true"
            - name: lb_enable
              value: "false"
          securityContext:
            capabilities:
              add: ["NET_ADMIN","SYS_TIME"]
