apiVersion: v1
kind: Service
metadata:
  name: kube-vip-metrics
  namespace: kube-system
  labels: { app: kube-vip }
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "2112"
    prometheus.io/path: "/metrics"
spec:
  clusterIP: None
  selector:
    app: kube-vip
  ports:
    - name: metrics
      port: 2112
      targetPort: 2112
